# Generated by Django 2.2.3 on 2019-07-10 08:02

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDoctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('doctor_name', models.CharField(max_length=50)),
                ('doctor_email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('doctor_workplace', models.CharField(max_length=100)),
                ('doctor_category', models.CharField(max_length=50)),
                ('doctor_degree', models.CharField(max_length=100)),
                ('doctor_gender', models.CharField(max_length=10)),
                ('doctor_age', models.CharField(max_length=3)),
                ('doctor_phone', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserPatient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('patient_area', models.CharField(max_length=30)),
                ('patient_blood', models.CharField(max_length=5)),
                ('patient_gender', models.CharField(max_length=10)),
                ('patient_age', models.CharField(max_length=3)),
                ('patient_phone', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
