# Generated by Django 2.2.3 on 2019-07-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdoctor',
            name='isDoctor',
            field=models.BooleanField(default=True),
        ),
    ]
