# Generated by Django 2.2.3 on 2019-07-10 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_userdoctor_isdoctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=50)),
                ('doctor_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='healthapp.UserDoctor')),
            ],
        ),
    ]
